cimport gl

# pyGLEW - Cython GLEW Wrapper for Python
#
# Copyright (C) 2012, Matthew Sitton
#               2012, Alex Marinescu
#
# LICENSED UNDER THE BSD LICENSE
#
# YOU SHOULD HAVE RECIEVED A COPY ALONG WITH THIS PROGRAM,
# SEE "LICENSE" FOR MORE INFORMATION.

#GL_PGI_misc_hints

GL_PGI_misc_hints = gl.GL_PGI_misc_hints

GL_PREFER_DOUBLEBUFFER_HINT_PGI = gl.GL_PREFER_DOUBLEBUFFER_HINT_PGI
GL_CONSERVE_MEMORY_HINT_PGI = gl.GL_CONSERVE_MEMORY_HINT_PGI
GL_RECLAIM_MEMORY_HINT_PGI = gl.GL_RECLAIM_MEMORY_HINT_PGI
GL_NATIVE_GRAPHICS_HANDLE_PGI = gl.GL_NATIVE_GRAPHICS_HANDLE_PGI
GL_NATIVE_GRAPHICS_BEGIN_HINT_PGI = gl.GL_NATIVE_GRAPHICS_BEGIN_HINT_PGI
GL_NATIVE_GRAPHICS_END_HINT_PGI = gl.GL_NATIVE_GRAPHICS_END_HINT_PGI
GL_ALWAYS_FAST_HINT_PGI = gl.GL_ALWAYS_FAST_HINT_PGI
GL_ALWAYS_SOFT_HINT_PGI = gl.GL_ALWAYS_SOFT_HINT_PGI
GL_ALLOW_DRAW_OBJ_HINT_PGI = gl.GL_ALLOW_DRAW_OBJ_HINT_PGI
GL_ALLOW_DRAW_WIN_HINT_PGI = gl.GL_ALLOW_DRAW_WIN_HINT_PGI
GL_ALLOW_DRAW_FRG_HINT_PGI = gl.GL_ALLOW_DRAW_FRG_HINT_PGI
GL_ALLOW_DRAW_MEM_HINT_PGI = gl.GL_ALLOW_DRAW_MEM_HINT_PGI
GL_STRICT_DEPTHFUNC_HINT_PGI = gl.GL_STRICT_DEPTHFUNC_HINT_PGI
GL_STRICT_LIGHTING_HINT_PGI = gl.GL_STRICT_LIGHTING_HINT_PGI
GL_STRICT_SCISSOR_HINT_PGI = gl.GL_STRICT_SCISSOR_HINT_PGI
GL_FULL_STIPPLE_HINT_PGI = gl.GL_FULL_STIPPLE_HINT_PGI
GL_CLIP_NEAR_HINT_PGI = gl.GL_CLIP_NEAR_HINT_PGI
GL_CLIP_FAR_HINT_PGI = gl.GL_CLIP_FAR_HINT_PGI
GL_WIDE_LINE_HINT_PGI = gl.GL_WIDE_LINE_HINT_PGI
GL_BACK_NORMALS_HINT_PGI = gl.GL_BACK_NORMALS_HINT_PGI

#GL_PGI_vertex_hints

GL_PGI_vertex_hints = gl.GL_PGI_vertex_hints

GL_VERTEX23_BIT_PGI = gl.GL_VERTEX23_BIT_PGI
GL_VERTEX4_BIT_PGI = gl.GL_VERTEX4_BIT_PGI
GL_COLOR3_BIT_PGI = gl.GL_COLOR3_BIT_PGI
GL_COLOR4_BIT_PGI = gl.GL_COLOR4_BIT_PGI
GL_EDGEFLAG_BIT_PGI = gl.GL_EDGEFLAG_BIT_PGI
GL_INDEX_BIT_PGI = gl.GL_INDEX_BIT_PGI
GL_MAT_AMBIENT_BIT_PGI = gl.GL_MAT_AMBIENT_BIT_PGI
GL_VERTEX_DATA_HINT_PGI = gl.GL_VERTEX_DATA_HINT_PGI
GL_VERTEX_CONSISTENT_HINT_PGI = gl.GL_VERTEX_CONSISTENT_HINT_PGI
GL_MATERIAL_SIDE_HINT_PGI = gl.GL_MATERIAL_SIDE_HINT_PGI
GL_MAX_VERTEX_HINT_PGI = gl.GL_MAX_VERTEX_HINT_PGI
GL_MAT_AMBIENT_AND_DIFFUSE_BIT_PGI = gl.GL_MAT_AMBIENT_AND_DIFFUSE_BIT_PGI
GL_MAT_DIFFUSE_BIT_PGI = gl.GL_MAT_DIFFUSE_BIT_PGI
GL_MAT_EMISSION_BIT_PGI = gl.GL_MAT_EMISSION_BIT_PGI
GL_MAT_COLOR_INDEXES_BIT_PGI = gl.GL_MAT_COLOR_INDEXES_BIT_PGI
GL_MAT_SHININESS_BIT_PGI = gl.GL_MAT_SHININESS_BIT_PGI
GL_MAT_SPECULAR_BIT_PGI = gl.GL_MAT_SPECULAR_BIT_PGI
GL_NORMAL_BIT_PGI = gl.GL_NORMAL_BIT_PGI
GL_TEXCOORD1_BIT_PGI = gl.GL_TEXCOORD1_BIT_PGI
GL_TEXCOORD2_BIT_PGI = gl.GL_TEXCOORD2_BIT_PGI
GL_TEXCOORD3_BIT_PGI = gl.GL_TEXCOORD3_BIT_PGI
GL_TEXCOORD4_BIT_PGI = gl.GL_TEXCOORD4_BIT_PGI