cimport gl

# pyGLEW - Cython GLEW Wrapper for Python
#
# Copyright (C) 2012, Matthew Sitton
#               2012, Alex Marinescu
#
# LICENSED UNDER THE BSD LICENSE
#
# YOU SHOULD HAVE RECIEVED A COPY ALONG WITH THIS PROGRAM,
# SEE "LICENSE" FOR MORE INFORMATION.

#GL_INGR_color_clamp

GL_INGR_color_clamp = gl.GL_INGR_color_clamp

GL_RED_MIN_CLAMP_INGR = gl.GL_RED_MIN_CLAMP_INGR
GL_GREEN_MIN_CLAMP_INGR = gl.GL_GREEN_MIN_CLAMP_INGR
GL_BLUE_MIN_CLAMP_INGR = gl.GL_BLUE_MIN_CLAMP_INGR
GL_ALPHA_MIN_CLAMP_INGR = gl.GL_ALPHA_MIN_CLAMP_INGR
GL_RED_MAX_CLAMP_INGR = gl.GL_RED_MAX_CLAMP_INGR
GL_GREEN_MAX_CLAMP_INGR = gl.GL_GREEN_MAX_CLAMP_INGR
GL_BLUE_MAX_CLAMP_INGR = gl.GL_BLUE_MAX_CLAMP_INGR
GL_ALPHA_MAX_CLAMP_INGR = gl.GL_ALPHA_MAX_CLAMP_INGR

#GL_INGR_interlace_read

GL_INGR_interlace_read = gl.GL_INGR_interlace_read

GL_INTERLACE_READ_INGR = gl.GL_INTERLACE_READ_INGR