cimport gl

# pyGLEW - Cython GLEW Wrapper for Python
#
# Copyright (C) 2012, Matthew Sitton
#               2012, Alex Marinescu
#
# LICENSED UNDER THE BSD LICENSE
#
# YOU SHOULD HAVE RECIEVED A COPY ALONG WITH THIS PROGRAM,
# SEE "LICENSE" FOR MORE INFORMATION.

#GL_OML_interlace

GL_OML_interlace = gl.GL_OML_interlace

GL_INTERLACE_OML = gl.GL_INTERLACE_OML
GL_INTERLACE_READ_OML = gl.GL_INTERLACE_READ_OML

#GL_OML_resample

GL_OML_resample = gl.GL_OML_resample

GL_PACK_RESAMPLE_OML = gl.GL_PACK_RESAMPLE_OML
GL_UNPACK_RESAMPLE_OML = gl.GL_UNPACK_RESAMPLE_OML
GL_RESAMPLE_REPLICATE_OML = gl.GL_RESAMPLE_REPLICATE_OML
GL_RESAMPLE_ZERO_FILL_OML = gl.GL_RESAMPLE_ZERO_FILL_OML
GL_RESAMPLE_AVERAGE_OML = gl.GL_RESAMPLE_AVERAGE_OML
GL_RESAMPLE_DECIMATE_OML = gl.GL_RESAMPLE_DECIMATE_OML

#GL_OML_subsample

GL_OML_subsample = gl.GL_OML_subsample

GL_FORMAT_SUBSAMPLE_24_24_OML = gl.GL_FORMAT_SUBSAMPLE_24_24_OML
GL_FORMAT_SUBSAMPLE_244_244_OML = gl.GL_FORMAT_SUBSAMPLE_244_244_OML