cimport gl

# pyGLEW - Cython GLEW Wrapper for Python
#
# Copyright (C) 2012, Matthew Sitton
#               2012, Alex Marinescu
#
# LICENSED UNDER THE BSD LICENSE
#
# YOU SHOULD HAVE RECIEVED A COPY ALONG WITH THIS PROGRAM,
# SEE "LICENSE" FOR MORE INFORMATION.

#error codes
GLEW_OK = gl.GLEW_OK
GLEW_NO_ERROR = gl.GLEW_NO_ERROR
GLEW_ERROR_NO_GL_VERSION = gl.GLEW_ERROR_NO_GL_VERSION    #missing GL ver = gl.GLEW_ERROR_NO_GL_VERSION    #missing GL ver
GLEW_ERROR_GL_VERSION_10_ONLY = gl.GLEW_ERROR_GL_VERSION_10_ONLY    #Need at least OpenGL = gl.GLEW_ERROR_GL_VERSION_10_ONLY    #Need at least OpenGL
GLEW_ERROR_GLX_VERSION_11_ONLY = gl.GLEW_ERROR_GLX_VERSION_11_ONLY    #Need at least GLX = gl.GLEW_ERROR_GLX_VERSION_11_ONLY    #Need at least GLX

#string codes
GLEW_VERSION = gl.GLEW_VERSION
GLEW_VERSION_MAJOR = gl.GLEW_VERSION_MAJOR
GLEW_VERSION_MINOR = gl.GLEW_VERSION_MINOR
GLEW_VERSION_MICRO = gl.GLEW_VERSION_MICRO

#API

#gl.GLenum glewInitA "glewInit"()
#gl.GLbyte* glewGetString "glewGetString(gl.GLenum name)
#gl.GLbyte* glewGetErrorString "glewGetErrorString"(gl.GLenum error)
#gl.GLboolean glewGetExtension "glewGetExtension"(char* name)
#gl.GLboolean glewIsSupported "glewIsSupported(char* name)

#def glewContextInit(ctx):
#    return gl.glewContextInit(<gl.GLEWContext*>ctx)

#def glewContextIsSupported(ctx, name):
#    cdef char* name1 = name
#    return gl.glewContextIsSupported(<gl.const_GLEWContext_ptr>ctx, name1)

def glewInit():
   return gl.glewInit()

def glewIsSupported(name):
    cdef char* name1 = name
    return gl.glewIsSupported(name1)

#def glewIsExtensionSupporte(A):
#    return gl.glewIsExtensionSupporte(A)

glewExperimental = gl.glewExperimental

def glewGetExtension(name):
    cdef char* name1 = name
    return gl.glewGetExtension(name1)

def glewGetErrorString(unsigned int error):
    cdef unsigned int* error1 = &error
    return gl.glewGetErrorString(error)

def glewGetString(name):
    return gl.glewGetString(name)

GLEW_VERSION_1_1 = gl.GLEW_VERSION_1_1
GLEW_VERSION_1_2 = gl.GLEW_VERSION_1_2
GLEW_VERSION_1_2_1 = gl.GLEW_VERSION_1_2_1
GLEW_VERSION_1_3 = gl.GLEW_VERSION_1_3
GLEW_VERSION_1_4 = gl.GLEW_VERSION_1_4
GLEW_VERSION_1_5 = gl.GLEW_VERSION_1_5
GLEW_VERSION_2_0 = gl.GLEW_VERSION_2_0
GLEW_VERSION_2_1 = gl.GLEW_VERSION_2_1
GLEW_VERSION_3_0 = gl.GLEW_VERSION_3_0
GLEW_VERSION_3_1 = gl.GLEW_VERSION_3_1
GLEW_VERSION_3_2 = gl.GLEW_VERSION_3_2
GLEW_VERSION_3_3 = gl.GLEW_VERSION_3_3
GLEW_VERSION_4_0 = gl.GLEW_VERSION_4_0
GLEW_VERSION_4_1 = gl.GLEW_VERSION_4_1
GLEW_VERSION_4_2 = gl.GLEW_VERSION_4_2
GLEW_3DFX_multisample = gl.GLEW_3DFX_multisample
GLEW_3DFX_tbuffer = gl.GLEW_3DFX_tbuffer
GLEW_3DFX_texture_compression_FXT1 = gl.GLEW_3DFX_texture_compression_FXT1
GLEW_AMD_blend_minmax_factor = gl.GLEW_AMD_blend_minmax_factor
GLEW_AMD_conservative_depth = gl.GLEW_AMD_conservative_depth
GLEW_AMD_debug_output = gl.GLEW_AMD_debug_output
GLEW_AMD_depth_clamp_separate = gl.GLEW_AMD_depth_clamp_separate
GLEW_AMD_draw_buffers_blend = gl.GLEW_AMD_draw_buffers_blend
GLEW_AMD_multi_draw_indirect = gl.GLEW_AMD_multi_draw_indirect
GLEW_AMD_name_gen_delete = gl.GLEW_AMD_name_gen_delete
GLEW_AMD_performance_monitor = gl.GLEW_AMD_performance_monitor
GLEW_AMD_sample_positions = gl.GLEW_AMD_sample_positions
GLEW_AMD_seamless_cubemap_per_texture = gl.GLEW_AMD_seamless_cubemap_per_texture
GLEW_AMD_shader_stencil_export = gl.GLEW_AMD_shader_stencil_export
GLEW_AMD_texture_texture4 = gl.GLEW_AMD_texture_texture4
GLEW_AMD_transform_feedback3_lines_triangles = gl.GLEW_AMD_transform_feedback3_lines_triangles
GLEW_AMD_vertex_shader_tessellator = gl.GLEW_AMD_vertex_shader_tessellator
GLEW_APPLE_aux_depth_stencil = gl.GLEW_APPLE_aux_depth_stencil
GLEW_APPLE_client_storage = gl.GLEW_APPLE_client_storage
GLEW_APPLE_element_array = gl.GLEW_APPLE_element_array
GLEW_APPLE_fence = gl.GLEW_APPLE_fence
GLEW_APPLE_float_pixels = gl.GLEW_APPLE_float_pixels
GLEW_APPLE_flush_buffer_range = gl.GLEW_APPLE_flush_buffer_range
GLEW_APPLE_object_purgeable = gl.GLEW_APPLE_object_purgeable
GLEW_APPLE_pixel_buffer = gl.GLEW_APPLE_pixel_buffer
GLEW_APPLE_rgb_422 = gl.GLEW_APPLE_rgb_422
GLEW_APPLE_row_bytes = gl.GLEW_APPLE_row_bytes
GLEW_APPLE_specular_vector = gl.GLEW_APPLE_specular_vector
GLEW_APPLE_texture_range = gl.GLEW_APPLE_texture_range
GLEW_APPLE_transform_hint = gl.GLEW_APPLE_transform_hint
GLEW_APPLE_vertex_array_object = gl.GLEW_APPLE_vertex_array_object
GLEW_APPLE_vertex_array_range = gl.GLEW_APPLE_vertex_array_range
GLEW_APPLE_vertex_program_evaluators = gl.GLEW_APPLE_vertex_program_evaluators
GLEW_APPLE_ycbcr_422 = gl.GLEW_APPLE_ycbcr_422
GLEW_ARB_ES2_compatibility = gl.GLEW_ARB_ES2_compatibility
GLEW_ARB_base_instance = gl.GLEW_ARB_base_instance
GLEW_ARB_blend_func_extended = gl.GLEW_ARB_blend_func_extended
GLEW_ARB_cl_event = gl.GLEW_ARB_cl_event
GLEW_ARB_color_buffer_float = gl.GLEW_ARB_color_buffer_float
GLEW_ARB_compatibility = gl.GLEW_ARB_compatibility
GLEW_ARB_compressed_texture_pixel_storage = gl.GLEW_ARB_compressed_texture_pixel_storage
GLEW_ARB_conservative_depth = gl.GLEW_ARB_conservative_depth
GLEW_ARB_copy_buffer = gl.GLEW_ARB_copy_buffer
GLEW_ARB_debug_output = gl.GLEW_ARB_debug_output
GLEW_ARB_depth_buffer_float = gl.GLEW_ARB_depth_buffer_float
GLEW_ARB_depth_clamp = gl.GLEW_ARB_depth_clamp
GLEW_ARB_depth_texture = gl.GLEW_ARB_depth_texture
GLEW_ARB_draw_buffers = gl.GLEW_ARB_draw_buffers
GLEW_ARB_draw_buffers_blend = gl.GLEW_ARB_draw_buffers_blend
GLEW_ARB_draw_elements_base_vertex = gl.GLEW_ARB_draw_elements_base_vertex
GLEW_ARB_draw_indirect = gl.GLEW_ARB_draw_indirect
GLEW_ARB_draw_instanced = gl.GLEW_ARB_draw_instanced
GLEW_ARB_explicit_attrib_location = gl.GLEW_ARB_explicit_attrib_location
GLEW_ARB_fragment_coord_conventions = gl.GLEW_ARB_fragment_coord_conventions
GLEW_ARB_fragment_program = gl.GLEW_ARB_fragment_program
GLEW_ARB_fragment_program_shadow = gl.GLEW_ARB_fragment_program_shadow
GLEW_ARB_fragment_shader = gl.GLEW_ARB_fragment_shader
GLEW_ARB_framebuffer_object = gl.GLEW_ARB_framebuffer_object
GLEW_ARB_framebuffer_sRGB = gl.GLEW_ARB_framebuffer_sRGB
GLEW_ARB_geometry_shader4 = gl.GLEW_ARB_geometry_shader4
GLEW_ARB_get_program_binary = gl.GLEW_ARB_get_program_binary
GLEW_ARB_gpu_shader5 = gl.GLEW_ARB_gpu_shader5
GLEW_ARB_gpu_shader_fp64 = gl.GLEW_ARB_gpu_shader_fp64
GLEW_ARB_half_float_pixel = gl.GLEW_ARB_half_float_pixel
GLEW_ARB_half_float_vertex = gl.GLEW_ARB_half_float_vertex
GLEW_ARB_imaging = gl.GLEW_ARB_imaging
GLEW_ARB_instanced_arrays = gl.GLEW_ARB_instanced_arrays
GLEW_ARB_internalformat_query = gl.GLEW_ARB_internalformat_query
GLEW_ARB_map_buffer_alignment = gl.GLEW_ARB_map_buffer_alignment
GLEW_ARB_map_buffer_range = gl.GLEW_ARB_map_buffer_range
GLEW_ARB_matrix_palette = gl.GLEW_ARB_matrix_palette
GLEW_ARB_multisample = gl.GLEW_ARB_multisample
GLEW_ARB_multitexture = gl.GLEW_ARB_multitexture
GLEW_ARB_occlusion_query = gl.GLEW_ARB_occlusion_query
GLEW_ARB_occlusion_query2 = gl.GLEW_ARB_occlusion_query2
GLEW_ARB_pixel_buffer_object = gl.GLEW_ARB_pixel_buffer_object
GLEW_ARB_point_parameters = gl.GLEW_ARB_point_parameters
GLEW_ARB_point_sprite = gl.GLEW_ARB_point_sprite
GLEW_ARB_provoking_vertex = gl.GLEW_ARB_provoking_vertex
GLEW_ARB_robustness = gl.GLEW_ARB_robustness
GLEW_ARB_sample_shading = gl.GLEW_ARB_sample_shading
GLEW_ARB_sampler_objects = gl.GLEW_ARB_sampler_objects
GLEW_ARB_seamless_cube_map = gl.GLEW_ARB_seamless_cube_map
GLEW_ARB_separate_shader_objects = gl.GLEW_ARB_separate_shader_objects
GLEW_ARB_shader_atomic_counters = gl.GLEW_ARB_shader_atomic_counters
GLEW_ARB_shader_bit_encoding = gl.GLEW_ARB_shader_bit_encoding
GLEW_ARB_shader_image_load_store = gl.GLEW_ARB_shader_image_load_store
GLEW_ARB_shader_objects = gl.GLEW_ARB_shader_objects
GLEW_ARB_shader_precision = gl.GLEW_ARB_shader_precision
GLEW_ARB_shader_stencil_export = gl.GLEW_ARB_shader_stencil_export
GLEW_ARB_shader_subroutine = gl.GLEW_ARB_shader_subroutine
GLEW_ARB_shader_texture_lod = gl.GLEW_ARB_shader_texture_lod
GLEW_ARB_shading_language_100 = gl.GLEW_ARB_shading_language_100
GLEW_ARB_shading_language_420pack = gl.GLEW_ARB_shading_language_420pack
GLEW_ARB_shading_language_include = gl.GLEW_ARB_shading_language_include
GLEW_ARB_shading_language_packing = gl.GLEW_ARB_shading_language_packing
GLEW_ARB_shadow = gl.GLEW_ARB_shadow
GLEW_ARB_shadow_ambient = gl.GLEW_ARB_shadow_ambient
GLEW_ARB_sync = gl.GLEW_ARB_sync
GLEW_ARB_tessellation_shader = gl.GLEW_ARB_tessellation_shader
GLEW_ARB_texture_border_clamp = gl.GLEW_ARB_texture_border_clamp
GLEW_ARB_texture_buffer_object = gl.GLEW_ARB_texture_buffer_object
GLEW_ARB_texture_buffer_object_rgb32 = gl.GLEW_ARB_texture_buffer_object_rgb32
GLEW_ARB_texture_compression = gl.GLEW_ARB_texture_compression
GLEW_ARB_texture_compression_bptc = gl.GLEW_ARB_texture_compression_bptc
GLEW_ARB_texture_compression_rgtc = gl.GLEW_ARB_texture_compression_rgtc
GLEW_ARB_texture_cube_map = gl.GLEW_ARB_texture_cube_map
GLEW_ARB_texture_cube_map_array = gl.GLEW_ARB_texture_cube_map_array
GLEW_ARB_texture_env_add = gl.GLEW_ARB_texture_env_add
GLEW_ARB_texture_env_combine = gl.GLEW_ARB_texture_env_combine
GLEW_ARB_texture_env_crossbar = gl.GLEW_ARB_texture_env_crossbar
GLEW_ARB_texture_env_dot3 = gl.GLEW_ARB_texture_env_dot3
GLEW_ARB_texture_float = gl.GLEW_ARB_texture_float
GLEW_ARB_texture_gather = gl.GLEW_ARB_texture_gather
GLEW_ARB_texture_mirrored_repeat = gl.GLEW_ARB_texture_mirrored_repeat
GLEW_ARB_texture_multisample = gl.GLEW_ARB_texture_multisample
GLEW_ARB_texture_non_power_of_two = gl.GLEW_ARB_texture_non_power_of_two
GLEW_ARB_texture_query_lod = gl.GLEW_ARB_texture_query_lod
GLEW_ARB_texture_rectangle = gl.GLEW_ARB_texture_rectangle
GLEW_ARB_texture_rg = gl.GLEW_ARB_texture_rg
GLEW_ARB_texture_rgb10_a2ui = gl.GLEW_ARB_texture_rgb10_a2ui
GLEW_ARB_texture_storage = gl.GLEW_ARB_texture_storage
GLEW_ARB_texture_swizzle = gl.GLEW_ARB_texture_swizzle
GLEW_ARB_timer_query = gl.GLEW_ARB_timer_query
GLEW_ARB_transform_feedback2 = gl.GLEW_ARB_transform_feedback2
GLEW_ARB_transform_feedback3 = gl.GLEW_ARB_transform_feedback3
GLEW_ARB_transform_feedback_instanced = gl.GLEW_ARB_transform_feedback_instanced
GLEW_ARB_transpose_matrix = gl.GLEW_ARB_transpose_matrix
GLEW_ARB_uniform_buffer_object = gl.GLEW_ARB_uniform_buffer_object
GLEW_ARB_vertex_array_bgra = gl.GLEW_ARB_vertex_array_bgra
GLEW_ARB_vertex_array_object = gl.GLEW_ARB_vertex_array_object
GLEW_ARB_vertex_attrib_64bit = gl.GLEW_ARB_vertex_attrib_64bit
GLEW_ARB_vertex_blend = gl.GLEW_ARB_vertex_blend
GLEW_ARB_vertex_buffer_object = gl.GLEW_ARB_vertex_buffer_object
GLEW_ARB_vertex_program = gl.GLEW_ARB_vertex_program
GLEW_ARB_vertex_shader = gl.GLEW_ARB_vertex_shader
GLEW_ARB_vertex_type_2_10_10_10_rev = gl.GLEW_ARB_vertex_type_2_10_10_10_rev
GLEW_ARB_viewport_array = gl.GLEW_ARB_viewport_array
GLEW_ARB_window_pos = gl.GLEW_ARB_window_pos
GLEW_ATIX_point_sprites = gl.GLEW_ATIX_point_sprites
GLEW_ATIX_texture_env_combine3 = gl.GLEW_ATIX_texture_env_combine3
GLEW_ATIX_texture_env_route = gl.GLEW_ATIX_texture_env_route
GLEW_ATIX_vertex_shader_output_point_size = gl.GLEW_ATIX_vertex_shader_output_point_size
GLEW_ATI_draw_buffers = gl.GLEW_ATI_draw_buffers
GLEW_ATI_element_array = gl.GLEW_ATI_element_array
GLEW_ATI_envmap_bumpmap = gl.GLEW_ATI_envmap_bumpmap
GLEW_ATI_fragment_shader = gl.GLEW_ATI_fragment_shader
GLEW_ATI_map_object_buffer = gl.GLEW_ATI_map_object_buffer
GLEW_ATI_meminfo = gl.GLEW_ATI_meminfo
GLEW_ATI_pn_triangles = gl.GLEW_ATI_pn_triangles
GLEW_ATI_separate_stencil = gl.GLEW_ATI_separate_stencil
GLEW_ATI_shader_texture_lod = gl.GLEW_ATI_shader_texture_lod
GLEW_ATI_text_fragment_shader = gl.GLEW_ATI_text_fragment_shader
GLEW_ATI_texture_compression_3dc = gl.GLEW_ATI_texture_compression_3dc
GLEW_ATI_texture_env_combine3 = gl.GLEW_ATI_texture_env_combine3
GLEW_ATI_texture_float = gl.GLEW_ATI_texture_float
GLEW_ATI_texture_mirror_once = gl.GLEW_ATI_texture_mirror_once
GLEW_ATI_vertex_array_object = gl.GLEW_ATI_vertex_array_object
GLEW_ATI_vertex_attrib_array_object = gl.GLEW_ATI_vertex_attrib_array_object
GLEW_ATI_vertex_streams = gl.GLEW_ATI_vertex_streams
GLEW_EXT_422_pixels = gl.GLEW_EXT_422_pixels
GLEW_EXT_Cg_shader = gl.GLEW_EXT_Cg_shader
GLEW_EXT_abgr = gl.GLEW_EXT_abgr
GLEW_EXT_bgra = gl.GLEW_EXT_bgra
GLEW_EXT_bindable_uniform = gl.GLEW_EXT_bindable_uniform
GLEW_EXT_blend_color = gl.GLEW_EXT_blend_color
GLEW_EXT_blend_equation_separate = gl.GLEW_EXT_blend_equation_separate
GLEW_EXT_blend_func_separate = gl.GLEW_EXT_blend_func_separate
GLEW_EXT_blend_logic_op = gl.GLEW_EXT_blend_logic_op
GLEW_EXT_blend_minmax = gl.GLEW_EXT_blend_minmax
GLEW_EXT_blend_subtract = gl.GLEW_EXT_blend_subtract
GLEW_EXT_clip_volume_hint = gl.GLEW_EXT_clip_volume_hint
GLEW_EXT_cmyka = gl.GLEW_EXT_cmyka
GLEW_EXT_color_subtable = gl.GLEW_EXT_color_subtable
GLEW_EXT_compiled_vertex_array = gl.GLEW_EXT_compiled_vertex_array
GLEW_EXT_convolution = gl.GLEW_EXT_convolution
GLEW_EXT_coordinate_frame = gl.GLEW_EXT_coordinate_frame
GLEW_EXT_copy_texture = gl.GLEW_EXT_copy_texture
GLEW_EXT_cull_vertex = gl.GLEW_EXT_cull_vertex
GLEW_EXT_depth_bounds_test = gl.GLEW_EXT_depth_bounds_test
GLEW_EXT_direct_state_access = gl.GLEW_EXT_direct_state_access
GLEW_EXT_draw_buffers2 = gl.GLEW_EXT_draw_buffers2
GLEW_EXT_draw_instanced = gl.GLEW_EXT_draw_instanced
GLEW_EXT_draw_range_elements = gl.GLEW_EXT_draw_range_elements
GLEW_EXT_fog_coord = gl.GLEW_EXT_fog_coord
GLEW_EXT_fragment_lighting = gl.GLEW_EXT_fragment_lighting
GLEW_EXT_framebuffer_blit = gl.GLEW_EXT_framebuffer_blit
GLEW_EXT_framebuffer_multisample = gl.GLEW_EXT_framebuffer_multisample
GLEW_EXT_framebuffer_multisample_blit_scaled = gl.GLEW_EXT_framebuffer_multisample_blit_scaled
GLEW_EXT_framebuffer_object = gl.GLEW_EXT_framebuffer_object
GLEW_EXT_framebuffer_sRGB = gl.GLEW_EXT_framebuffer_sRGB
GLEW_EXT_geometry_shader4 = gl.GLEW_EXT_geometry_shader4
GLEW_EXT_gpu_program_parameters = gl.GLEW_EXT_gpu_program_parameters
GLEW_EXT_gpu_shader4 = gl.GLEW_EXT_gpu_shader4
GLEW_EXT_histogram = gl.GLEW_EXT_histogram
GLEW_EXT_index_array_formats = gl.GLEW_EXT_index_array_formats
GLEW_EXT_index_func = gl.GLEW_EXT_index_func
GLEW_EXT_index_material = gl.GLEW_EXT_index_material
GLEW_EXT_index_texture = gl.GLEW_EXT_index_texture
GLEW_EXT_light_texture = gl.GLEW_EXT_light_texture
GLEW_EXT_misc_attribute = gl.GLEW_EXT_misc_attribute
GLEW_EXT_multi_draw_arrays = gl.GLEW_EXT_multi_draw_arrays
GLEW_EXT_multisample = gl.GLEW_EXT_multisample
GLEW_EXT_packed_depth_stencil = gl.GLEW_EXT_packed_depth_stencil
GLEW_EXT_packed_float = gl.GLEW_EXT_packed_float
GLEW_EXT_packed_pixels = gl.GLEW_EXT_packed_pixels
GLEW_EXT_paletted_texture = gl.GLEW_EXT_paletted_texture
GLEW_EXT_pixel_buffer_object = gl.GLEW_EXT_pixel_buffer_object
GLEW_EXT_pixel_transform = gl.GLEW_EXT_pixel_transform
GLEW_EXT_pixel_transform_color_table = gl.GLEW_EXT_pixel_transform_color_table
GLEW_EXT_point_parameters = gl.GLEW_EXT_point_parameters
GLEW_EXT_polygon_offset = gl.GLEW_EXT_polygon_offset
GLEW_EXT_provoking_vertex = gl.GLEW_EXT_provoking_vertex
GLEW_EXT_rescale_normal = gl.GLEW_EXT_rescale_normal
GLEW_EXT_scene_marker = gl.GLEW_EXT_scene_marker
GLEW_EXT_secondary_color = gl.GLEW_EXT_secondary_color
GLEW_EXT_separate_shader_objects = gl.GLEW_EXT_separate_shader_objects
GLEW_EXT_separate_specular_color = gl.GLEW_EXT_separate_specular_color
GLEW_EXT_shader_image_load_store = gl.GLEW_EXT_shader_image_load_store
GLEW_EXT_shadow_funcs = gl.GLEW_EXT_shadow_funcs
GLEW_EXT_shared_texture_palette = gl.GLEW_EXT_shared_texture_palette
GLEW_EXT_stencil_clear_tag = gl.GLEW_EXT_stencil_clear_tag
GLEW_EXT_stencil_two_side = gl.GLEW_EXT_stencil_two_side
GLEW_EXT_stencil_wrap = gl.GLEW_EXT_stencil_wrap
GLEW_EXT_subtexture = gl.GLEW_EXT_subtexture
GLEW_EXT_texture = gl.GLEW_EXT_texture
GLEW_EXT_texture3D = gl.GLEW_EXT_texture3D
GLEW_EXT_texture_array = gl.GLEW_EXT_texture_array
GLEW_EXT_texture_buffer_object = gl.GLEW_EXT_texture_buffer_object
GLEW_EXT_texture_compression_dxt1 = gl.GLEW_EXT_texture_compression_dxt1
GLEW_EXT_texture_compression_latc = gl.GLEW_EXT_texture_compression_latc
GLEW_EXT_texture_compression_rgtc = gl.GLEW_EXT_texture_compression_rgtc
GLEW_EXT_texture_compression_s3tc = gl.GLEW_EXT_texture_compression_s3tc
GLEW_EXT_texture_cube_map = gl.GLEW_EXT_texture_cube_map
GLEW_EXT_texture_edge_clamp = gl.GLEW_EXT_texture_edge_clamp
GLEW_EXT_texture_env = gl.GLEW_EXT_texture_env
GLEW_EXT_texture_env_add = gl.GLEW_EXT_texture_env_add
GLEW_EXT_texture_env_combine = gl.GLEW_EXT_texture_env_combine
GLEW_EXT_texture_env_dot3 = gl.GLEW_EXT_texture_env_dot3
GLEW_EXT_texture_filter_anisotropic = gl.GLEW_EXT_texture_filter_anisotropic
GLEW_EXT_texture_integer = gl.GLEW_EXT_texture_integer
GLEW_EXT_texture_lod_bias = gl.GLEW_EXT_texture_lod_bias
GLEW_EXT_texture_mirror_clamp = gl.GLEW_EXT_texture_mirror_clamp
GLEW_EXT_texture_object = gl.GLEW_EXT_texture_object
GLEW_EXT_texture_perturb_normal = gl.GLEW_EXT_texture_perturb_normal
GLEW_EXT_texture_rectangle = gl.GLEW_EXT_texture_rectangle
GLEW_EXT_texture_sRGB = gl.GLEW_EXT_texture_sRGB
GLEW_EXT_texture_sRGB_decode = gl.GLEW_EXT_texture_sRGB_decode
GLEW_EXT_texture_shared_exponent = gl.GLEW_EXT_texture_shared_exponent
GLEW_EXT_texture_snorm = gl.GLEW_EXT_texture_snorm
GLEW_EXT_texture_swizzle = gl.GLEW_EXT_texture_swizzle
GLEW_EXT_timer_query = gl.GLEW_EXT_timer_query
GLEW_EXT_transform_feedback = gl.GLEW_EXT_transform_feedback
GLEW_EXT_vertex_array = gl.GLEW_EXT_vertex_array
GLEW_EXT_vertex_array_bgra = gl.GLEW_EXT_vertex_array_bgra
GLEW_EXT_vertex_attrib_64bit = gl.GLEW_EXT_vertex_attrib_64bit
GLEW_EXT_vertex_shader = gl.GLEW_EXT_vertex_shader
GLEW_EXT_vertex_weighting = gl.GLEW_EXT_vertex_weighting
GLEW_EXT_x11_sync_object = gl.GLEW_EXT_x11_sync_object
GLEW_GREMEDY_frame_terminator = gl.GLEW_GREMEDY_frame_terminator
GLEW_GREMEDY_string_marker = gl.GLEW_GREMEDY_string_marker
GLEW_HP_convolution_border_modes = gl.GLEW_HP_convolution_border_modes
GLEW_HP_image_transform = gl.GLEW_HP_image_transform
GLEW_HP_occlusion_test = gl.GLEW_HP_occlusion_test
GLEW_HP_texture_lighting = gl.GLEW_HP_texture_lighting
GLEW_IBM_cull_vertex = gl.GLEW_IBM_cull_vertex
GLEW_IBM_multimode_draw_arrays = gl.GLEW_IBM_multimode_draw_arrays
GLEW_IBM_rasterpos_clip = gl.GLEW_IBM_rasterpos_clip
GLEW_IBM_static_data = gl.GLEW_IBM_static_data
GLEW_IBM_texture_mirrored_repeat = gl.GLEW_IBM_texture_mirrored_repeat
GLEW_IBM_vertex_array_lists = gl.GLEW_IBM_vertex_array_lists
GLEW_INGR_color_clamp = gl.GLEW_INGR_color_clamp
GLEW_INGR_interlace_read = gl.GLEW_INGR_interlace_read
GLEW_INTEL_parallel_arrays = gl.GLEW_INTEL_parallel_arrays
GLEW_INTEL_texture_scissor = gl.GLEW_INTEL_texture_scissor
GLEW_KTX_buffer_region = gl.GLEW_KTX_buffer_region
GLEW_MESAX_texture_stack = gl.GLEW_MESAX_texture_stack
GLEW_MESA_pack_invert = gl.GLEW_MESA_pack_invert
GLEW_MESA_resize_buffers = gl.GLEW_MESA_resize_buffers
GLEW_MESA_window_pos = gl.GLEW_MESA_window_pos
GLEW_MESA_ycbcr_texture = gl.GLEW_MESA_ycbcr_texture
GLEW_NVX_gpu_memory_info = gl.GLEW_NVX_gpu_memory_info
GLEW_NV_blend_square = gl.GLEW_NV_blend_square
GLEW_NV_conditional_render = gl.GLEW_NV_conditional_render
GLEW_NV_copy_depth_to_color = gl.GLEW_NV_copy_depth_to_color
GLEW_NV_copy_image = gl.GLEW_NV_copy_image
GLEW_NV_depth_buffer_float = gl.GLEW_NV_depth_buffer_float
GLEW_NV_depth_clamp = gl.GLEW_NV_depth_clamp
GLEW_NV_depth_range_unclamped = gl.GLEW_NV_depth_range_unclamped
GLEW_NV_evaluators = gl.GLEW_NV_evaluators
GLEW_NV_explicit_multisample = gl.GLEW_NV_explicit_multisample
GLEW_NV_fence = gl.GLEW_NV_fence
GLEW_NV_float_buffer = gl.GLEW_NV_float_buffer
GLEW_NV_fog_distance = gl.GLEW_NV_fog_distance
GLEW_NV_fragment_program = gl.GLEW_NV_fragment_program
GLEW_NV_fragment_program2 = gl.GLEW_NV_fragment_program2
GLEW_NV_fragment_program4 = gl.GLEW_NV_fragment_program4
GLEW_NV_fragment_program_option = gl.GLEW_NV_fragment_program_option
GLEW_NV_framebuffer_multisample_coverage = gl.GLEW_NV_framebuffer_multisample_coverage
GLEW_NV_geometry_program4 = gl.GLEW_NV_geometry_program4
GLEW_NV_geometry_shader4 = gl.GLEW_NV_geometry_shader4
GLEW_NV_gpu_program4 = gl.GLEW_NV_gpu_program4
GLEW_NV_gpu_program5 = gl.GLEW_NV_gpu_program5
GLEW_NV_gpu_program_fp64 = gl.GLEW_NV_gpu_program_fp64
GLEW_NV_gpu_shader5 = gl.GLEW_NV_gpu_shader5
GLEW_NV_half_float = gl.GLEW_NV_half_float
GLEW_NV_light_max_exponent = gl.GLEW_NV_light_max_exponent
GLEW_NV_multisample_coverage = gl.GLEW_NV_multisample_coverage
GLEW_NV_multisample_filter_hint = gl.GLEW_NV_multisample_filter_hint
GLEW_NV_occlusion_query = gl.GLEW_NV_occlusion_query
GLEW_NV_packed_depth_stencil = gl.GLEW_NV_packed_depth_stencil
GLEW_NV_parameter_buffer_object = gl.GLEW_NV_parameter_buffer_object
GLEW_NV_parameter_buffer_object2 = gl.GLEW_NV_parameter_buffer_object2
GLEW_NV_path_rendering = gl.GLEW_NV_path_rendering
GLEW_NV_pixel_data_range = gl.GLEW_NV_pixel_data_range
GLEW_NV_point_sprite = gl.GLEW_NV_point_sprite
GLEW_NV_present_video = gl.GLEW_NV_present_video
GLEW_NV_primitive_restart = gl.GLEW_NV_primitive_restart
GLEW_NV_register_combiners = gl.GLEW_NV_register_combiners
GLEW_NV_register_combiners2 = gl.GLEW_NV_register_combiners2
GLEW_NV_shader_buffer_load = gl.GLEW_NV_shader_buffer_load
GLEW_NV_tessellation_program5 = gl.GLEW_NV_tessellation_program5
GLEW_NV_texgen_emboss = gl.GLEW_NV_texgen_emboss
GLEW_NV_texgen_reflection = gl.GLEW_NV_texgen_reflection
GLEW_NV_texture_barrier = gl.GLEW_NV_texture_barrier
GLEW_NV_texture_compression_vtc = gl.GLEW_NV_texture_compression_vtc
GLEW_NV_texture_env_combine4 = gl.GLEW_NV_texture_env_combine4
GLEW_NV_texture_expand_normal = gl.GLEW_NV_texture_expand_normal
GLEW_NV_texture_multisample = gl.GLEW_NV_texture_multisample
GLEW_NV_texture_rectangle = gl.GLEW_NV_texture_rectangle
GLEW_NV_texture_shader = gl.GLEW_NV_texture_shader
GLEW_NV_texture_shader2 = gl.GLEW_NV_texture_shader2
GLEW_NV_texture_shader3 = gl.GLEW_NV_texture_shader3
GLEW_NV_transform_feedback = gl.GLEW_NV_transform_feedback
GLEW_NV_transform_feedback2 = gl.GLEW_NV_transform_feedback2
GLEW_NV_vdpau_interop = gl.GLEW_NV_vdpau_interop
GLEW_NV_vertex_array_range = gl.GLEW_NV_vertex_array_range
GLEW_NV_vertex_array_range2 = gl.GLEW_NV_vertex_array_range2
GLEW_NV_vertex_attrib_integer_64bit = gl.GLEW_NV_vertex_attrib_integer_64bit
GLEW_NV_vertex_buffer_unified_memory = gl.GLEW_NV_vertex_buffer_unified_memory
GLEW_NV_vertex_program = gl.GLEW_NV_vertex_program
GLEW_NV_vertex_program1_1 = gl.GLEW_NV_vertex_program1_1
GLEW_NV_vertex_program2 = gl.GLEW_NV_vertex_program2
GLEW_NV_vertex_program2_option = gl.GLEW_NV_vertex_program2_option
GLEW_NV_vertex_program3 = gl.GLEW_NV_vertex_program3
GLEW_NV_vertex_program4 = gl.GLEW_NV_vertex_program4
GLEW_NV_video_capture = gl.GLEW_NV_video_capture
GLEW_OES_byte_coordinates = gl.GLEW_OES_byte_coordinates
GLEW_OES_compressed_paletted_texture = gl.GLEW_OES_compressed_paletted_texture
GLEW_OES_read_format = gl.GLEW_OES_read_format
GLEW_OES_single_precision = gl.GLEW_OES_single_precision
GLEW_OML_interlace = gl.GLEW_OML_interlace
GLEW_OML_resample = gl.GLEW_OML_resample
GLEW_OML_subsample = gl.GLEW_OML_subsample
GLEW_PGI_misc_hints = gl.GLEW_PGI_misc_hints
GLEW_PGI_vertex_hints = gl.GLEW_PGI_vertex_hints
GLEW_REND_screen_coordinates = gl.GLEW_REND_screen_coordinates
GLEW_S3_s3tc = gl.GLEW_S3_s3tc
GLEW_SGIS_color_range = gl.GLEW_SGIS_color_range
GLEW_SGIS_detail_texture = gl.GLEW_SGIS_detail_texture
GLEW_SGIS_fog_function = gl.GLEW_SGIS_fog_function
GLEW_SGIS_generate_mipmap = gl.GLEW_SGIS_generate_mipmap
GLEW_SGIS_multisample = gl.GLEW_SGIS_multisample
GLEW_SGIS_pixel_texture = gl.GLEW_SGIS_pixel_texture
GLEW_SGIS_point_line_texgen = gl.GLEW_SGIS_point_line_texgen
GLEW_SGIS_sharpen_texture = gl.GLEW_SGIS_sharpen_texture
GLEW_SGIS_texture4D = gl.GLEW_SGIS_texture4D
GLEW_SGIS_texture_border_clamp = gl.GLEW_SGIS_texture_border_clamp
GLEW_SGIS_texture_edge_clamp = gl.GLEW_SGIS_texture_edge_clamp
GLEW_SGIS_texture_filter4 = gl.GLEW_SGIS_texture_filter4
GLEW_SGIS_texture_lod = gl.GLEW_SGIS_texture_lod
GLEW_SGIS_texture_select = gl.GLEW_SGIS_texture_select
GLEW_SGIX_async = gl.GLEW_SGIX_async
GLEW_SGIX_async_histogram = gl.GLEW_SGIX_async_histogram
GLEW_SGIX_async_pixel = gl.GLEW_SGIX_async_pixel
GLEW_SGIX_blend_alpha_minmax = gl.GLEW_SGIX_blend_alpha_minmax
GLEW_SGIX_clipmap = gl.GLEW_SGIX_clipmap
GLEW_SGIX_convolution_accuracy = gl.GLEW_SGIX_convolution_accuracy
GLEW_SGIX_depth_texture = gl.GLEW_SGIX_depth_texture
GLEW_SGIX_flush_raster = gl.GLEW_SGIX_flush_raster
GLEW_SGIX_fog_offset = gl.GLEW_SGIX_fog_offset
GLEW_SGIX_fog_texture = gl.GLEW_SGIX_fog_texture
GLEW_SGIX_fragment_specular_lighting = gl.GLEW_SGIX_fragment_specular_lighting
GLEW_SGIX_framezoom = gl.GLEW_SGIX_framezoom
GLEW_SGIX_interlace = gl.GLEW_SGIX_interlace
GLEW_SGIX_ir_instrument1 = gl.GLEW_SGIX_ir_instrument1
GLEW_SGIX_list_priority = gl.GLEW_SGIX_list_priority
GLEW_SGIX_pixel_texture = gl.GLEW_SGIX_pixel_texture
GLEW_SGIX_pixel_texture_bits = gl.GLEW_SGIX_pixel_texture_bits
GLEW_SGIX_reference_plane = gl.GLEW_SGIX_reference_plane
GLEW_SGIX_resample = gl.GLEW_SGIX_resample
GLEW_SGIX_shadow = gl.GLEW_SGIX_shadow
GLEW_SGIX_shadow_ambient = gl.GLEW_SGIX_shadow_ambient
GLEW_SGIX_sprite = gl.GLEW_SGIX_sprite
GLEW_SGIX_tag_sample_buffer = gl.GLEW_SGIX_tag_sample_buffer
GLEW_SGIX_texture_add_env = gl.GLEW_SGIX_texture_add_env
GLEW_SGIX_texture_coordinate_clamp = gl.GLEW_SGIX_texture_coordinate_clamp
GLEW_SGIX_texture_lod_bias = gl.GLEW_SGIX_texture_lod_bias
GLEW_SGIX_texture_multi_buffer = gl.GLEW_SGIX_texture_multi_buffer
GLEW_SGIX_texture_range = gl.GLEW_SGIX_texture_range
GLEW_SGIX_texture_scale_bias = gl.GLEW_SGIX_texture_scale_bias
GLEW_SGIX_vertex_preclip = gl.GLEW_SGIX_vertex_preclip
GLEW_SGIX_vertex_preclip_hint = gl.GLEW_SGIX_vertex_preclip_hint
GLEW_SGIX_ycrcb = gl.GLEW_SGIX_ycrcb
GLEW_SGI_color_matrix = gl.GLEW_SGI_color_matrix
GLEW_SGI_color_table = gl.GLEW_SGI_color_table
GLEW_SGI_texture_color_table = gl.GLEW_SGI_texture_color_table
GLEW_SUNX_constant_data = gl.GLEW_SUNX_constant_data
GLEW_SUN_convolution_border_modes = gl.GLEW_SUN_convolution_border_modes
GLEW_SUN_global_alpha = gl.GLEW_SUN_global_alpha
GLEW_SUN_mesh_array = gl.GLEW_SUN_mesh_array
GLEW_SUN_read_video_pixels = gl.GLEW_SUN_read_video_pixels
GLEW_SUN_slice_accum = gl.GLEW_SUN_slice_accum
GLEW_SUN_triangle_list = gl.GLEW_SUN_triangle_list
GLEW_SUN_vertex = gl.GLEW_SUN_vertex
GLEW_WIN_phong_shading = gl.GLEW_WIN_phong_shading
GLEW_WIN_specular_fog = gl.GLEW_WIN_specular_fog