cimport gl

# pyGLEW - Cython GLEW Wrapper for Python
#
# Copyright (C) 2012, Matthew Sitton
#               2012, Alex Marinescu
#
# LICENSED UNDER THE BSD LICENSE
#
# YOU SHOULD HAVE RECIEVED A COPY ALONG WITH THIS PROGRAM,
# SEE "LICENSE" FOR MORE INFORMATION.

#GL_S3_s3tc

GL_S3_s3tc = gl.GL_S3_s3tc

GL_RGB_S3TC = gl.GL_RGB_S3TC
GL_RGB4_S3TC = gl.GL_RGB4_S3TC
GL_RGBA_S3TC = gl.GL_RGBA_S3TC
GL_RGBA4_S3TC = gl.GL_RGBA4_S3TC
GL_RGBA_DXT5_S3TC = gl.GL_RGBA_DXT5_S3TC
GL_RGBA4_DXT5_S3TC = gl.GL_RGBA4_DXT5_S3TC